name: Java CI

on:
  push:
    branches:
      - main
      - nenad_sonar_cloud_dev


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'New folder/document-review/document-review'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          GITHUB_TOKEN: ${{secrets.GIT_TOKEN}}
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
        with:
          projectBaseDir: 'New folder/document-review/document-review'
          args: >
            -Dsonar.organization=nenadgolubovic
            -Dsonar.projectKey=Document_review_software_Automated
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
            -Dsonar.java.binaries=target/classes